# Generated by Django 6.1.2 on 2026-10-06 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('categoria', models.CharField(choices=[('Herramientas manuales', 'Herramientas manuales'), ('Herramientas eléctricas', 'Herramientas eléctricas'), ('Fijaciones', 'Fijaciones'), ('Pinturas', 'Pinturas'), ('Electricidad', 'Electricidad'), ('Seguridad', 'Seguridad'), ('Construcción', 'Construcción'), ('Jardín', 'Jardín')], max_length=50, verbose_name='categoría')),
                ('precio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(150000)], verbose_name='precio en pesos chilenos')),
                ('stock', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='unidades en stock')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['nombre'],
            },
        ),
    ]
