# Generated by Django 6.1.2 on 2026-10-06 19:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_fondo', models.CharField(default='#f3f5f7', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingresa un color hexadecimal, por ejemplo #f3f5f7.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='color de fondo')),
            ],
            options={
                'verbose_name': 'configuración del sitio',
                'verbose_name_plural': 'configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='ConsultaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='consulta')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='fecha de envío')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='catalogo.producto', verbose_name='producto de interés')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_ferreteria', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'consulta de cliente',
                'verbose_name_plural': 'consultas de clientes',
                'ordering': ['-creada_en'],
            },
        ),
    ]
