# Generated by Django 6.1.2 on 2026-10-07 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_configuracion_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=240, verbose_name='notificación')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('leido', models.BooleanField(default=False, verbose_name='leído')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_ferreteria', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'notificación de cliente',
                'verbose_name_plural': 'notificaciones de clientes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100, verbose_name='producto comprado')),
                ('precio_unitario', models.PositiveIntegerField(verbose_name='precio unitario')),
                ('cantidad', models.PositiveSmallIntegerField(verbose_name='cantidad')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='fecha de compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='catalogo.producto', verbose_name='producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_ferreteria', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'compra',
                'verbose_name_plural': 'compras',
                'ordering': ['-creada_en'],
            },
        ),
    ]
